/*
 *******************************************************************************
 *
 * Copyright (C) 2016 Dialog Semiconductor, unpublished work. This computer
 * program includes Confidential, Proprietary Information and is a Trade
 * Secret of Dialog Semiconductor. All use, disclosure, and/or reproduction
 * is prohibited unless authorized in writing. All Rights Reserved.
 *
 * bluetooth.support@diasemi.com
 *
 *******************************************************************************
 */

#ifndef BluetoothDefines_h
#define BluetoothDefines_h



#define DIALOG_SMARTEXITE_LIGHT_SERVICE_UUID                0xFFB0
#define DIALOG_SMARTEXITE_LIGHT_TOGGLE_UUID                 0xFFB1
#define DIALOG_SMARTEXITE_LIGHT_VALUE_UUID                  0xFFB2
#define DIALOG_SMARTEXITE_BATTERY_VALUE_UUID                0xFFB3

#define ORG_BLUETOOTH_SERVICE_HEALTH_THERMOMETER            0x1809

#define ORG_BLUETOOTH_SERVICE_ALERT_LEVEL                   0x2A06

#define ORG_BLUETOOTH_SERVICE_IMMEDIATE_ALERT               0x1802
#define ORG_BLUETOOTH_SERVICE_LINK_LOSS                     0x1803
#define ORG_BLUETOOTH_SERVICE_TX_POWER                      0x1804

#define ORG_BLUETOOTH_SERVICE_BATTERY_SERVICE               0x180F
#define ORG_BLUETOOTH_SERVICE_BATTERY_LEVEL                 0x2A19

#define DIALOG_WEARABLES_SERVICE                            @"2ea78970-7d44-44bb-b097-26183f402400"
#define DIALOG_WEARABLES_CHARACTERISTIC_ACCELEROMETER       @"2ea78970-7d44-44bb-b097-26183f402401"
#define DIALOG_WEARABLES_CHARACTERISTIC_GYROSCOPE           @"2ea78970-7d44-44bb-b097-26183f402402"
#define DIALOG_WEARABLES_CHARACTERISTIC_MAGNETOMETER        @"2ea78970-7d44-44bb-b097-26183f402403"
#define DIALOG_WEARABLES_CHARACTERISTIC_BAROMETER           @"2ea78970-7d44-44bb-b097-26183f402404"
#define DIALOG_WEARABLES_CHARACTERISTIC_HUMIDITY            @"2ea78970-7d44-44bb-b097-26183f402405"
#define DIALOG_WEARABLES_CHARACTERISTIC_TEMPERATURE         @"2ea78970-7d44-44bb-b097-26183f402406"
#define DIALOG_WEARABLES_CHARACTERISTIC_SENSOR_FUSION       @"2ea78970-7d44-44bb-b097-26183f402407"
#define DIALOG_WEARABLES_CHARACTERISTIC_FEATURES            @"2ea78970-7d44-44bb-b097-26183f402408"
#define DIALOG_WEARABLES_CHARACTERISTIC_CONTROL             @"2ea78970-7d44-44bb-b097-26183f402409"
#define DIALOG_WEARABLES_CHARACTERISTIC_CONTROL_NOTIFY      @"2ea78970-7d44-44bb-b097-26183f40240a"

#define DIALOG_WEARABLES_COMMAND_CONFIGURATION_STOP                 0
#define DIALOG_WEARABLES_COMMAND_CONFIGURATION_START                1
#define DIALOG_WEARABLES_COMMAND_CONFIGURATION_READ_NV              2
#define DIALOG_WEARABLES_COMMAND_CONFIGURATION_RESET_TO_DEFAULTS    3
#define DIALOG_WEARABLES_COMMAND_CONFIGURATION_STORE_NV             4
#define DIALOG_WEARABLES_COMMAND_CONFIGURATION_RUNNING_STATE        6
#define DIALOG_WEARABLES_COMMAND_CONFIGURATION_WRITE                10
#define DIALOG_WEARABLES_COMMAND_CONFIGURATION_READ                 11

#define DIALOG_WEARABLES_COMMAND_CALIBRATION_STORE_NV               5
#define DIALOG_WEARABLES_COMMAND_CALIBRATION_RESET_TO_DEFAULTS      7

#define DIALOG_WEARABLES_COMMAND_CALIBRATION_SFL_COEFFICIENTS_WRITE 12
#define DIALOG_WEARABLES_COMMAND_CALIBRATION_SFL_COEFFICIENTS_READ  13
#define DIALOG_WEARABLES_COMMAND_CALIBRATION_COEFFICIENTS_WRITE     14
#define DIALOG_WEARABLES_COMMAND_CALIBRATION_COEFFICIENTS_READ      15
#define DIALOG_WEARABLES_COMMAND_CALIBRATION_CONTROL_WRITE          16
#define DIALOG_WEARABLES_COMMAND_CALIBRATION_CONTROL_READ           17
#define DIALOG_WEARABLES_COMMAND_CALIBRATION_ACCELEROMETER_START    18

#define DIALOG_WEARABLES_COMMAND_CALIBRATION_STORE_NV               5


#endif /* BluetoothDefines_h */
